// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetDeployEnvHandlerFunc turns a function with the right signature into a get deploy env handler
type GetDeployEnvHandlerFunc func(GetDeployEnvParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDeployEnvHandlerFunc) Handle(params GetDeployEnvParams) middleware.Responder {
	return fn(params)
}

// GetDeployEnvHandler interface for that can handle valid get deploy env params
type GetDeployEnvHandler interface {
	Handle(GetDeployEnvParams) middleware.Responder
}

// NewGetDeployEnv creates a new http.Handler for the get deploy env operation
func NewGetDeployEnv(ctx *middleware.Context, handler GetDeployEnvHandler) *GetDeployEnv {
	return &GetDeployEnv{Context: ctx, Handler: handler}
}

/*GetDeployEnv swagger:route GET /deploy/env getDeployEnv

Get the deployment environment

*/
type GetDeployEnv struct {
	Context *middleware.Context
	Handler GetDeployEnvHandler
}

func (o *GetDeployEnv) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetDeployEnvParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
