// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetJokeByIDHandlerFunc turns a function with the right signature into a get joke by id handler
type GetJokeByIDHandlerFunc func(GetJokeByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetJokeByIDHandlerFunc) Handle(params GetJokeByIDParams) middleware.Responder {
	return fn(params)
}

// GetJokeByIDHandler interface for that can handle valid get joke by id params
type GetJokeByIDHandler interface {
	Handle(GetJokeByIDParams) middleware.Responder
}

// NewGetJokeByID creates a new http.Handler for the get joke by id operation
func NewGetJokeByID(ctx *middleware.Context, handler GetJokeByIDHandler) *GetJokeByID {
	return &GetJokeByID{Context: ctx, Handler: handler}
}

/*GetJokeByID swagger:route GET /jokes/{id} getJokeById

Get the joke with the specified id

*/
type GetJokeByID struct {
	Context *middleware.Context
	Handler GetJokeByIDHandler
}

func (o *GetJokeByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetJokeByIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
