// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetIPAddressesHandlerFunc turns a function with the right signature into a get IP addresses handler
type GetIPAddressesHandlerFunc func(GetIPAddressesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetIPAddressesHandlerFunc) Handle(params GetIPAddressesParams) middleware.Responder {
	return fn(params)
}

// GetIPAddressesHandler interface for that can handle valid get IP addresses params
type GetIPAddressesHandler interface {
	Handle(GetIPAddressesParams) middleware.Responder
}

// NewGetIPAddresses creates a new http.Handler for the get IP addresses operation
func NewGetIPAddresses(ctx *middleware.Context, handler GetIPAddressesHandler) *GetIPAddresses {
	return &GetIPAddresses{Context: ctx, Handler: handler}
}

/*GetIPAddresses swagger:route GET /system/ipaddresses getIpAddresses

Get the IP addresses of the host

*/
type GetIPAddresses struct {
	Context *middleware.Context
	Handler GetIPAddressesHandler
}

func (o *GetIPAddresses) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetIPAddressesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
