// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi ICNDB
ICNDB sample API for ITB


    Schemes:
      http
    Host: localhost
    BasePath: /api
    Version: 0.0.1

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
