name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - uses: actions/checkout@v3

      - name: Run go generate
        run: go generate ./...

      - uses: ko-build/setup-ko@v0.6
      - run: ko build --bare --tags "$GITHUB_SHA" --tags latest